### ISSUE TITLE
Template for report to Publisher

### ISSUE THREAD

**Issue by notshi** [codeforIATI/iati-data-bugtracker#11]
When contacting the publisher and/or IATI Support, it would be good to have an email/issue template to use.

**Comment by markbrough** [comment]
Here's a very rough first version based on a recent bug report. What do you think of this? Maybe just to add to the bottom of the issue template for easy copy+pasting? Or just provide a link from there to a .md file in the root of this repository?

---

### Template email you can use to contact a publisher

**TO: Use IATI Registry Publisher email address if you don't have an existing contact.**

**SUBJECT: `SUMMARY OF ISSUE` in `PUBLISHER NAME` IATI data files**

Dear `NAME OF PUBLISHER`,

I wanted to get in touch with you as there appears to be an error in your IATI data.

```
BRIEF DESCRIPTION OF ERROR
e.g. There appear to be a large number of duplicate IATI Identifiers in your files. It appears that the same activities are being published twice.
```

For example, in this file:
`LINK TO FILE`

```
BRIEF DESCRIPTION OF ISSUE IN ONE FILE
e.g. In this file, there are 183 activities but only 125 unique identifiers.
```

You can also see this information on the IATI Dashboard for your publisher:
```
PUBLISHER URL ON DASHBOARD, OPTIONALLY WITH BRIEF DESCRIPTION OF WHAT YOU CAN SEE THERE
e.g.
http://dashboard.iatistandard.org/publisher/aics.html
You can see here that across all of your published data, there are 7386 activities, but only 5246 of these are unique (the numbers should be the same):
```

All the best

`YOUR NAME`

**Comment by notshi** [comment]
This is great, thank you!

I think a link should suffice as it might make the bug report template confusing and lengthy otherwise.
However, I would definitely appreciate seeing it there for copy+pasting convenience and it might encourage others to contact publishers when they report an issue here.

**Comment by andylolz** [comment]
Nice! I’ve sent a PR adding it as a link, but I don’t know which is best really.
