### ISSUE TITLE
FEATURE: make it easier to pull out data on particular publishers

### ISSUE THREAD

**Issue by markbrough** [codeforIATI/iati-data-bugtracker#18]
It would be nice to be able to pull out all tickets related to particular publishers, e.g. in order to make https://github.com/codeforIATI/IATI-Dashboard/issues/28 possible.

We could do this via labels (e.g. `publisher:worldbank`) or perhaps frontmatter. I guess the former would be nicer so that we can also search on Github Issues for a particular publisher?

**Comment by andylolz** [comment]
Yes absolutely – I think @matmaxgeds also suggested this.

I wonder if we can do it with frontmatter, and then get a bot to create the labels?? (I basically want to get a load of bots to help manage tickets in this repo.)

**Comment by andylolz** [comment]
> We could do this via labels (e.g. publisher:worldbank)

We’ve added lots of labels that use this format now! The list is not auto-updated, so we’ll have to update it in the future.

**Comment by andylolz** [comment]
> We could do this via labels (e.g. publisher:worldbank)

I’ve added lots of labels that use this format now (not quite right yet… But I am hoping the settings app will sort this out!)

**Comment by andylolz** [comment]
I gave up with the settings app! I’ve made a python script and a daily github action instead.

I think this is done – closing!

**Comment by markbrough** [comment]
I missed this -- this is super nice!!
