### ISSUE TITLE
New labels added that start with something after 'P' are too hard to find.......

### ISSUE THREAD

**Issue by matmaxgeds** [codeforIATI/iati-data-bugtracker#20]
If you know the name of the label you are after you can just start typing, but e.g. if we had one called 'verified_issue' and you didn't know it was there, you would never see it below all the 'publisher: xx' ones.......maybe we can either maintain a list of them somewhere, or start all the 'meta' ones with "_" or "AA_" or similar as a fudge to make them appear at the top

**Comment by andylolz** [comment]
Ha, yeah, I went back and forth on this!

There’s a complete list here: https://github.com/codeforIATI/iati-data-bugtracker/labels

I couldn’t decide what was the best && neatest way to do this, so I copped out and prefixed everything with “publisher: ” Fortunately, there are (currently at least) none after ‘P’, so this isn’t a problem yet…

If it becomes a problem, it’s not too much faff to either rename all the publisher labels, or prefix them, or prefix the non-publisher labels…

**Comment by andylolz** [comment]
I reckon we can close this, and we should worry about it once we have labels that start with something after ‘P’! (If that happens, it is possible to rename publisher labels.)
